name: astha
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_it: ^7.6.0
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  riverpod_infinite_scroll: ^1.0.9
  cached_network_image: ^3.2.3
  page_transition: ^2.0.9
  sliver_tools: ^0.2.10
  auto_route: ^7.4.0


dev_dependencies: 
  flutter_lints: ^2.0.0
  auto_route_generator: 
  build_runner: 
  flutter_test: 
    sdk: flutter
dependency_overrides:


flutter: 
  uses-material-design: true

